### ISSUE TITLE
Feature Request: Allow Observation Space to be an array

### ISSUE THREAD

**Issue by Xaoilin** [PufferAI/PufferLib#55]
Context: Running and training Pokemon Red

It would be helpful for us to change the Pokemon Red code to allow the observation space to take more than just a Box as an input. Currently I am working with something like this:

```
        self.observation_space = spaces.Dict({
            'screen': spaces.Box(low=0, high=255, shape=self.output_full, dtype=np.uint8),
            'player_coords': self.create_box(0, 255, (2,), np.int32),
            'map_details': self.create_box(0, 255, (1,), np.int32),
        })
```

However the entire pipeline for running this command breaks:

`python demo.py --env pokemon_red --vectorization multiprocessing --track --wandb-entity YOUR_WANDB_USERNAME`

I spent hours trying to update the code to use a Dict for the observation space however was unsuccessful.

**Comment by jsuarez5341** [comment]
Pufferlib does support dict spaces, quite well in fact. Need more details on the error. Come chat on the Discord, you will get answers much faster
